version: "3"

services:

  rac1:
    container_name: rac1
    image: node:14
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - REACT_APP_GA_CODE="UA-129704402-1"
    volumes:
      - ./app:/home/node/app
      - ./docs:/home/node/docs
    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true
    command: "yarn start"

  rac1-static:
    container_name: rac1-static
    image: nginx
    volumes:
      - ./docs:/usr/share/nginx/html/Rac1.js/
    ports:
      - "0.0.0.0:4000:80"
