import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

const basePath = process.env.VITE_BASE_PATH || '/'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'logo-rac1.png', 'logo-rac1-maskable.png'],
      manifest: {
        short_name: "Rac1",
        name: "Rac1 radio podcast player",
        description: "Rac1 radio podcasts finder and player",
        lang: "en-US",
        icons: [
          {
            src: "favicon.ico",
            sizes: "128x128 64x64 32x32 24x24 16x16",
            type: "image/x-icon"
          },
          {
            src: "logo-rac1.png",
            sizes: "640x640",
            type: "image/png"
          },
          {
            src: "logo-rac1-maskable.png",
            sizes: "984x984",
            type: "image/png",
            purpose: "any maskable"
          }
        ],
        start_url: basePath,
        scope: basePath,
        display: "standalone",
        theme_color: "#000000",
        background_color: "#282c34"
      },
      workbox: {
        // Precache all assets generated by Vite
        globPatterns: ['**/*.{js,css,html,ico,png,svg,json}'],
        // App shell pattern - navigate to index.html for all routes
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/_/, /\/[^/?]+\.[^/]+$/],
        // Runtime caching for images
        runtimeCaching: [
          {
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif)$/,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'images',
              expiration: {
                maxEntries: 50,
              },
            },
          },
          {
            // Cache API responses if needed
            urlPattern: /^https:\/\/api\.audioteca\.rac1\.cat\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'api-cache',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24, // 24 hours
              },
            },
          },
        ],
        // Skip waiting on message
        skipWaiting: true,
        clientsClaim: true,
      },
    }),
  ],
  assetsInclude: ['**/Modals/*.html'], // This tells Vite to treat HTML as assets
  build: {
    outDir: 'build', // CRA's default build output
    // Ensure assets are properly hashed
    rollupOptions: {
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash].[ext]'
      }
    },
    // Generate sourcemaps for debugging
    sourcemap: true,
    // Chunk size warning limit
    chunkSizeWarningLimit: 1000,
    rollupOptions: {
      output: {
        // Split code into chunks for better caching
        manualChunks(id) {
          // Vendor chunks for node_modules
          if (id.includes('node_modules')) {
            // React vendor
            if (id.includes('react') || id.includes('react-dom') || id.includes('react-router')) {
              return 'react-vendor'
            }
            // UI vendor
            if (id.includes('react-modal') || id.includes('react-burger-menu') || 
              id.includes('rc-slider') || id.includes('rc-switch') ||
              id.includes('react-audio-player')) {
              return 'ui-vendor'
            }
            // Other vendors
            return 'vendor'
          }
        }
      },
    },
  },
  server: {
    host: true,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.js',
  },
})
