# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      # Can we use '**.md' ?
      - 'README.md'
      - 'SECURITY.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'app/README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]

jobs:
  pre_ci:
    name: Prepare CI environment
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.pr_get_commit_message.outputs.commit_message }}

    steps:

    - name: Checkout Project
      uses: actions/checkout@v4
      with:
        # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
        fetch-depth: 2

    - name: "Get commit message"
      id: pr_get_commit_message
      env:
        COMMIT_PUSH: ${{ github.event.head_commit.message }}
      run: |
        COMMIT_MESSAGE="${COMMIT_PUSH:-$(git log --format=%B -n 1 HEAD^2)}"
        echo -e "Commit message: \n${COMMIT_MESSAGE}\n\n"
        cat <<EOF >> "${GITHUB_OUTPUT}"
        commit_message<<END_OF_OUTPUT
        ${COMMIT_MESSAGE}
        END_OF_OUTPUT
        EOF

        echo "GITHUB_OUTPUT contents:"
        cat "${GITHUB_OUTPUT}"

  test-build:

    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Manage cache
      uses: actions/cache@v4
      with:
        path: |
          app/node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.OS }}-build

    - name: yarn install and build
      env:
        REACT_APP_GA_CODE: "UA-129704402-1"
      working-directory: ./app
      run: |
        yarn install
        yarn build

    - uses: actions/upload-artifact@v4
      # Same condition as `publish`job
      if: ${{ !contains(github.event.head_commit.message, '#no-publish') && (( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) || github.ref == 'refs/heads/main' ) }}
      with:
        name: built-app
        path: docs
        if-no-files-found: error
        retention-days: 5

  test-code:

    name: Test code and generate test coverage value
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Map a step output to a job output
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
      coverage-rounded-display: ${{ steps.coverage.outputs.coverage-rounded-display }}

    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Manage cache
      uses: actions/cache@v4
      with:
        path: |
          app/node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.OS }}-build

    - name: yarn install and test
      env:
        REACT_APP_GA_CODE: "UA-129704402-1"
      working-directory: ./app
      run: |
        yarn install
        yarn test --color --coverage

    # Coverage badges will be updated on any branch
    # and saved into a dedicated one
    - name: Check test coverage
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      id: coverage
      with:
        percentage: 50
        exit: 0
        rounded-precision: 2
        filename: "app/coverage/clover.xml"

  test:
    name: Tests waiter
    needs: [test-code, test-build]
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ needs.test-code.outputs.coverage }}
      coverage-rounded-display: ${{ needs.test-code.outputs.coverage-rounded-display }}
    steps:
    - name: Check test coverage
      env:
        COVERAGE: ${{ needs.test-code.outputs.coverage }}
        COVERAGE_ROUNDED: ${{ needs.test-code.outputs.coverage-rounded-display }}
      run: |
        echo "Coverage: ${COVERAGE}"
        echo "Coverage Rounded: ${COVERAGE_ROUNDED}"

  #comment_pr:
  #  name: Comment on PR with test coverage value
  #  needs: [test, pre_ci]
  #  if: ${{ github.event_name == 'pull_request' && github.actor == github.repository_owner && !contains(needs.pre_ci.outputs.commit_message, '#comment-badge') }}

  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Generate comment file with test coverage
  #    shell: bash
  #    env:
  #      COVERAGE: ${{ needs.test.outputs.coverage-rounded-display }}
  #    run: |
  #      echo "**Test coverage: ${COVERAGE}**" > output.md

  #  - name: Comment PR with test coverage
  #    uses: machine-learning-apps/pr-comment@1.0.0
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #    with:
  #      path: output.md

  badge:

    # Only generate and publish if these conditions are met:
    # - The test step ended successfully
    # - One of these is met:
    #   - This is a pull request event and the pull actor is the same as the repo owner
    #   - This is a push event and the push event is on branch 'main'
    name: Generate badge image with test coverage value
    needs: test
    if: ${{ ( github.event_name == 'pull_request' && github.actor == github.repository_owner ) || github.ref == 'refs/heads/main' }}
    outputs:
      url: ${{ steps.url.outputs.url }}
      markdown: ${{ steps.url.outputs.markdown }}

    runs-on: ubuntu-latest

    steps:

    - name: Extract branch name
      shell: bash
      run: |
        TMP_PULL_HEAD_REF="${{ github.head_ref }}"
        TMP_GITHUB_REF="${GITHUB_REF#refs/heads/}"
        EXPORT_VALUE=""
        if [ "${TMP_PULL_HEAD_REF}" != "" ]
        then
            EXPORT_VALUE="${TMP_PULL_HEAD_REF}"
        else
            EXPORT_VALUE="${TMP_GITHUB_REF}"
        fi
        echo "branch=${EXPORT_VALUE}" >> "${GITHUB_OUTPUT}"
      id: extract_branch

    - uses: actions/checkout@v4
      with:
        ref: badges
        path: badges

    # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v2.0.3
      id: badge
      with:
        label: 'Coverage'
        status: ${{ needs.test.outputs.coverage-rounded-display }}
        color: ${{
          needs.test.outputs.coverage > 90 && 'green'              ||
          needs.test.outputs.coverage > 80 && 'yellow,green'       ||
          needs.test.outputs.coverage > 70 && 'yellow'             ||
          needs.test.outputs.coverage > 60 && 'orange,yellow'      ||
          needs.test.outputs.coverage > 50 && 'orange'             ||
          needs.test.outputs.coverage > 40 && 'red,orange'         ||
          needs.test.outputs.coverage > 30 && 'red,red,orange'     ||
          needs.test.outputs.coverage > 20 && 'red,red,red,orange' ||
          'red' }}
        path: badges/test-coverage.svg

    - name: Commit badge
      env:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
        FILE: 'test-coverage.svg'
      working-directory: ./badges
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        mkdir -p "${BRANCH}"
        mv "${FILE}" "${BRANCH}"
        git add "${BRANCH}/${FILE}"

        # Will give error if badge did not changed
        git commit -m "Add/Update badge" || true

    - name: Push badge commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: badges
        directory: badges

    - name: Badge image URL
      id: url
      env:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
        FILE: 'test-coverage.svg'
        COVERAGE: ${{ needs.test.outputs.coverage-rounded-display }}
      run: |
        URL="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/badges/${BRANCH}/${FILE}"
        MARKDOWN="![Coverage ${COVERAGE}](${URL})"
        echo "Badge URL: ${URL}"
        echo "Badge image for Markdown: ${MARKDOWN}"
        echo "url=${URL}" >> "${GITHUB_OUTPUT}"
        echo "markdown=${MARKDOWN}" >> "${GITHUB_OUTPUT}"

  comment_pr_badge:
    name: Comment on PR with generated badge
    needs: [pre_ci, badge]
    if: ${{ github.event_name == 'pull_request' && contains(needs.pre_ci.outputs.commit_message, '#comment-badge') }}

    runs-on: ubuntu-latest

    steps:
    - name: Generate comment file with test coverage badge
      shell: bash
      env:
        BADGE: ${{ needs.badge.outputs.markdown }}
      run: |
        echo "Badge: ${BADGE}"
        echo "${BADGE}" > output.md

    - name: Comment PR with test coverage badge
      uses: machine-learning-apps/pr-comment@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: output.md

  publish:

    # Only generate and publish if these conditions are met:
    # - Commit message does not contains #no-publish
    # - The test step ended successfully
    # - One of these is met:
    #   - This is a pull request event and the pull has been merged
    #   - This is a push event and the push event is on branch 'main'
    name: Publish code to GitHub Pages
    needs: [pre_ci, test]
    if: ${{ !contains(github.event.head_commit.message, '#no-publish') && (( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) || github.ref == 'refs/heads/main' ) }}

    runs-on: ubuntu-latest

    steps:

    - name: Download built app from artifact
      uses: actions/download-artifact@v4
      with:
        name: built-app
        path: docs

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
