# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Manage cache
      uses: actions/cache@v2.0.0
      with:
        path: app/node_modules
        key: Rac1.js

    - name: yarn install and test
      run: |
        cd app
        yarn install
        yarn test --coverage

    # Coverage badges will be updated on any branch except protected
    # branches 'develop' and 'master' and on a pull requests
    - name: Test angular action
      uses:  demyanets/angular-coverage-badges-action@v1
      with:
        # The GITHUB_TOKEN secret.
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: app/coverage/coverage-final.json
        badges-directory: .github/badges/

    - name: Coverage monitor
      uses: slavcodev/coverage-monitor-action@1.1.0
      with:
        # The GITHUB_TOKEN secret.
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        # Path to Clover XML file.
        clover_file: app/coverage/clover.xml
        # Whether check the coverage thresholds.
        check: true
        # Whether comment the coverage report.
        comment: true
        # Mark the build as unstable when coverage is less than this threshold.
        threshold_alert: 50
        # Warning when coverage is less than this threshold.
        threshold_warning: 90
        # A string label to differentiate this status from the status of other systems.
        status_context: Coverage Report
        # A string label to differentiate the comment posted by this action.
        comment_context: Coverage Report
        # A mode for comments, supported: `replace`, `update` or `insert`.
        comment_mode: replace


  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Manage cache
      uses: actions/cache@v2.0.0
      with:
        path: app/node_modules
        key: Rac1.js

    - name: yarn install and build
      run: |
        cd app
        yarn install
        yarn build

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
